
import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico } from "next/font/google";
import "./globals.css";

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Readdy Site",
  description: "Generated by Readdy",
  icons: {
    icon: [
      {
        url: "https://readdy.ai/api/search-image?query=modern%20minimalist%20home%20construction%20logo%20icon%20with%20warm%20orange%20and%20blue%20colors%2C%20simple%20geometric%20house%20shape%20with%20clean%20lines%2C%20professional%20and%20trustworthy%20design%2C%20white%20background%2C%20centered%20composition%2C%20architectural%20elements%2C%20safe%20and%20reliable%20feeling%2C%20contemporary%20style%2C%20perfect%20for%20home%20renovation%20business&width=32&height=32&seq=favicon-32&orientation=squarish",
        sizes: "32x32",
        type: "image/png",
      },
      {
        url: "https://readdy.ai/api/search-image?query=modern%20minimalist%20home%20construction%20logo%20icon%20with%20warm%20orange%20and%20blue%20colors%2C%20simple%20geometric%20house%20shape%20with%20clean%20lines%2C%20professional%20and%20trustworthy%20design%2C%20white%20background%2C%20centered%20composition%2C%20architectural%20elements%2C%20safe%20and%20reliable%20feeling%2C%20contemporary%20style%2C%20perfect%20for%20home%20renovation%20business&width=16&height=16&seq=favicon-16&orientation=squarish",
        sizes: "16x16",
        type: "image/png",
      },
    ],
    apple: [
      {
        url: "https://readdy.ai/api/search-image?query=modern%20minimalist%20home%20construction%20logo%20icon%20with%20warm%20orange%20and%20blue%20colors%2C%20simple%20geometric%20house%20shape%20with%20clean%20lines%2C%20professional%20and%20trustworthy%20design%2C%20white%20background%2C%20centered%20composition%2C%20architectural%20elements%2C%20safe%20and%20reliable%20feeling%2C%20contemporary%20style%2C%20perfect%20for%20home%20renovation%20business&width=180&height=180&seq=apple-touch-icon&orientation=squarish",
        sizes: "180x180",
        type: "image/png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
